"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment overrides from <backend>/.env (gitignored).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'shenoflow-dev-secret-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'api.logistics.shenodev.tech,localhost,127.0.0.1,.vercel.app',
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'accounts',
    'orders',
    'invoices',
    'fleet',
    'notifications',
]

AUTH_USER_MODEL = 'accounts.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = os.environ.get(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'https://logistics.shenodev.tech,https://admin.logistics.shenodev.tech,http://localhost:3000',
).split(',')
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://logistics.shenodev.tech,https://admin.logistics.shenodev.tech,http://localhost:3000',
).split(',')

# Session cookie shared with the Nuxt frontend (httpOnly JWT in ``shenoflow_session``).
AUTH_COOKIE_NAME = os.environ.get('DJANGO_AUTH_COOKIE_NAME', 'shenoflow_session')
AUTH_COOKIE_SECURE = os.environ.get('DJANGO_AUTH_COOKIE_SECURE', 'true').lower() == 'true'
AUTH_COOKIE_DOMAIN = os.environ.get('DJANGO_AUTH_COOKIE_DOMAIN', '') or None
AUTH_COOKIE_SAMESITE = 'lax'
# The session cookie carries the short-lived access token (15 minutes).
AUTH_COOKIE_MAX_AGE = 60 * 15
# The long-lived refresh token is kept in its own httpOnly cookie (7 days).
AUTH_REFRESH_COOKIE_NAME = 'shenoflow_refresh'
AUTH_REFRESH_COOKIE_MAX_AGE = 60 * 60 * 24 * 7

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.SessionCookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Priority:
#   1. ``DATABASE_URL`` (e.g. Supabase Postgres via the transaction pooler on :6543)
#   2. ``SUPABASE_DB_PASSWORD`` + ``SUPABASE_URL`` — builds the pooler connection URL
#   3. Local SQLite (default, no env required)

SUPABASE_URL = os.environ.get('SUPABASE_URL', '').rstrip('/')
SUPABASE_DB_PASSWORD = os.environ.get('SUPABASE_DB_PASSWORD', '')

if os.environ.get('DATABASE_URL'):
    DATABASE_URL = os.environ['DATABASE_URL']
elif SUPABASE_DB_PASSWORD and '.' in SUPABASE_URL:
    project_ref = SUPABASE_URL.replace('https://', '').split('.')[0]
    db_region = os.environ.get('SUPABASE_DB_REGION', '')
    db_host = (
        f'aws-0-{db_region}.pooler.supabase.com'
        if db_region
        else f'{project_ref}.pooler.supabase.com'
    )
    DATABASE_URL = (
        f'postgresql://postgres.{project_ref}:{SUPABASE_DB_PASSWORD}'
        f'@{db_host}:6543/postgres'
    )
else:
    DATABASE_URL = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"

DATABASES = {
    'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=60),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Stripe — Visa refunds for cancelled orders (Admin only)
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_API_VERSION = os.environ.get('STRIPE_API_VERSION', '2024-06-20')

# Celery + Upstash Redis — automated driver dispatch (round-robin with timeout)
# Upstash Redis URL is provided as REDIS_URL or UPSTASH_REDIS_URL (rediss://...)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL') or os.environ.get('UPSTASH_REDIS_URL') or os.environ.get('REDIS_URL', 'memory://')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND') or os.environ.get('UPSTASH_REDIS_URL') or os.environ.get('REDIS_URL', 'cache+memory://')
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'false').lower() == 'true'
# For local dev without Redis, eager mode runs tasks synchronously (no broker needed)
if CELERY_BROKER_URL in ('memory://', '', None):
    CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Resend — transactional emails (from hello@contact.logistics.shenodev.tech)
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
RESEND_FROM_EMAIL = os.environ.get('RESEND_FROM_EMAIL', 'hello@contact.logistics.shenodev.tech')
RESEND_FROM_NAME = os.environ.get('RESEND_FROM_NAME', 'Sheno Logistics')

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
