# Generated by Django 6.1.1 on 2026-09-20 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Human readable order number e.g. SHP-10001-ORD', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received (Stage 1 — استلام الطلب)'), ('picked_up', 'Picked Up (Stage 2)'), ('in_transit', 'In Transit (Stage 3)'), ('out_for_delivery', 'Out for Delivery (Stage 4)'), ('delivered', 'Delivered (Stage 5)'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20)),
                ('origin', models.CharField(default='Rotterdam', max_length=120)),
                ('origin_code', models.CharField(default='RTM', max_length=10)),
                ('destination', models.CharField(default='Chicago', max_length=120)),
                ('destination_code', models.CharField(default='ORD', max_length=10)),
                ('mode', models.CharField(default='Ocean Freight', max_length=30)),
                ('priority', models.CharField(default='Standard Freight', max_length=30)),
                ('gross_weight', models.CharField(default='12,400 kg', max_length=30)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('refunded', 'Refunded')], db_index=True, default='none', max_length=10)),
                ('refund_id', models.CharField(blank=True, max_length=64, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Assigned driver (role=driver), set via dispatch board', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Customer who owns the order (role=user)', limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(fields=['owner', 'status'], name='orders_orde_owner_i_93b549_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['received', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'cancelled'])), name='order_status_valid', violation_error_message='Invalid order status')],
            },
        ),
    ]
