# Generated by Django 6.1.1 on 2026-09-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Original Visa PaymentIntent (pi_...) for Stripe refund', max_length=64, null=True),
        ),
    ]
