# Generated by Django 6.1.1 on 2026-09-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='+1 (212) 555-0148', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], db_index=True, default='assigned', help_text='Driver delivery status, cycles assigned→picked_up→on_the_way→delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_address',
            field=models.CharField(default='Rotterdam, RTM • Bay 04 • Pickup Dock 4', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_name',
            field=models.CharField(default='Rotterdam Hub Kitchen', max_length=120),
        ),
    ]
