# Generated by Django 6.1.1 on 2026-09-21 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_status_valid',
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_driver_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_driver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_in_progress',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_queue',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of driver IDs for round-robin'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('dispatching', 'Dispatching'), ('assigned', 'Assigned to Driver'), ('completed', 'Completed')], db_index=True, default='idle', help_text='Round-robin dispatch state', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, Cancel is disabled globally (after driver Accept)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing (قيد التنفيذ) — Stage 0'), ('received', 'Received (Stage 1 — استلام الطلب)'), ('picked_up', 'Picked Up (Stage 2)'), ('in_transit', 'In Transit (Stage 3)'), ('out_for_delivery', 'Out for Delivery (Stage 4)'), ('delivered', 'Delivered (Stage 5)'), ('cancelled', 'Cancelled'), ('received_by_driver', 'Received by Driver (مستلم من السائق)')], db_index=True, default='processing', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['processing', 'received', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'cancelled', 'received_by_driver'])), name='order_status_valid', violation_error_message='Invalid order status'),
        ),
    ]
