# Generated by Django 6.1.1 on 2026-09-20 08:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('user', models.OneToOneField(help_text='Driver user (role=driver)', limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('license_number', models.CharField(help_text='CDL or local license', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{5,20}$', 'Invalid license number')])),
                ('vehicle_type', models.CharField(choices=[('sprinter_van', 'Sprinter Van'), ('box_truck_5t', '5 Ton Box Truck'), ('box_truck_10t', '10 Ton Freight Rig'), ('heavy_tractor', 'Heavy Freight Tractor'), ('ev_sprinter', 'EV Sprinter 350'), ('volvo_fh_electric', 'Volvo FH Electric 40T')], default='sprinter_van', max_length=20)),
                ('vehicle_plate', models.CharField(help_text='License plate e.g. NY-784-KLP', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s().-]{7,25}$', 'Invalid phone')])),
                ('availability', models.CharField(choices=[('available', 'Available'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('on_break', 'On Break')], db_index=True, default='available', max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='Quick toggle for dispatch board')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, help_text='Driver rating 0.0–5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('acceptance_rate', models.DecimalField(decimal_places=1, default=100.0, help_text='Acceptance rate %', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_orders_count', models.PositiveSmallIntegerField(default=0)),
                ('max_orders', models.PositiveSmallIntegerField(default=5, help_text='Max concurrent orders for capacity check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'driver profile',
                'verbose_name_plural': 'driver profiles',
                'ordering': ['user__email'],
                'indexes': [models.Index(fields=['availability', 'is_available'], name='fleet_drive_availab_51a474_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='driver_rating_range'), models.CheckConstraint(condition=models.Q(('current_orders_count__lte', models.F('max_orders'))), name='driver_capacity_check', violation_error_message='Driver is at max capacity')],
            },
        ),
    ]
