# Generated by Django 6.1.1 on 2026-09-20 08:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Human readable invoice e.g. INV-2024-10004', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refund_id', models.CharField(blank=True, help_text='Stripe refund ID if refunded', max_length=64, null=True)),
                ('description', models.CharField(blank=True, help_text='e.g. Ocean Freight · SHP-10001-ORD', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Linked order, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order')),
                ('user', models.ForeignKey(help_text='Owner of the invoice', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='invoices_in_status_874ef9_idx'), models.Index(fields=['user', 'status'], name='invoices_in_user_id_ebcfda_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='invoice_amount_non_negative'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'paid', 'overdue', 'refunded', 'cancelled'])), name='invoice_status_valid')],
            },
        ),
    ]
